return {
	textNode = 1,
	insertNode = 2,
	functionNode = 3,
	snippetNode = 4,
	choiceNode = 5,
	dynamicNode = 6,
	snippet = 7,
	exitNode = 8,
	restoreNode = 9,
	node_types = { 1, 2, 3, 4, 5, 6, 7, 8, 9 },
	names = {
		"textNode",
		"insertNode",
		"functionNode",
		"snippetNode",
		"choiceNode",
		"dynamicNode",
		"snippet",
		"exitNode",
		"restoreNode",
	},
	names_pascal_case = {
		"TextNode",
		"InsertNode",
		"FunctionNode",
		"SnippetNode",
		"ChoiceNode",
		"DynamicNode",
		"Snippet",
		"ExitNode",
		"RestoreNode",
	},
}
