---
name: Check spelling

on:
  pull_request:
    branches: ["master"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v30
      - run: nix develop -i -c bash -c 'make spellcheck'
